FROM ubuntu:22.04

WORKDIR /tmp

RUN apt update && apt-get install wget curl nmap -y
RUN wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb

RUN apt update
RUN apt install powershell -y
RUN  pwsh -command Set-PSrepository PSGallery -InstallationPolicy Trusted
RUN  pwsh -command Install-module az -confirm:\$FALSE -verbose
RUN rm -rf /tmp/*
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
RUN  pwsh -command Set-PSrepository PSGallery -InstallationPolicy Untrusted
RUN  pwsh -command Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
ENTRYPOINT [ "pwsh","-noexit","-command","Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete" ]
